-- MySQL Script generated by MySQL Workbench
-- 01/11/17 18:30:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Meet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Meet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Meet` ;
USE `Meet` ;

-- -----------------------------------------------------
-- Table `Meet`.`Team Total Points`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Meet`.`Team_Total_Points` (
  `idTeam_Total_Points` INT NOT NULL AUTO_INCREMENT,
  `points` FLOAT NULL,
  PRIMARY KEY (`idTeam_Total_Points`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Meet`.`Teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Meet`.`Teams` (
  `idTeams` INT NOT NULL AUTO_INCREMENT,
  `team_name` VARCHAR(45) NULL,
  `team_points` INT NULL,
  PRIMARY KEY (`idTeams`),
  INDEX `fk_Teams_Team_Total_Points1_idx` (`team_points` ASC),
  CONSTRAINT `fk_Teams_Team_Total_Points`
    FOREIGN KEY (`team_points`)
    REFERENCES `Meet`.`Team_Total_Points` (`idTeam_Total_Points`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Meet`.`Athlete Total Points`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Meet`.`Athlete_Total_Points` (
  `idAthlete_Total_Points` INT NOT NULL AUTO_INCREMENT,
  `points` FLOAT NULL,
  PRIMARY KEY (`idAthlete_Total_Points`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Meet`.`Athletes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Meet`.`Athletes` (
  `idAthletes` INT NOT NULL AUTO_INCREMENT,
  `athlete_name` VARCHAR(45) NULL,
  `team` INT NULL,
  `athlete_points` INT NULL,
  PRIMARY KEY (`idAthletes`),
  INDEX `team_idx` (`team` ASC),
  INDEX `fk_Athletes_Athlete Total Points1_idx` (`athlete_points` ASC),
  CONSTRAINT `fk_Athletes_Team`
    FOREIGN KEY (`team`)
    REFERENCES `Meet`.`Teams` (`idTeams`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Athletes_Athlete_Total_Points`
    FOREIGN KEY (`athlete_points`)
    REFERENCES `Meet`.`Athlete_Total_Points` (`idAthlete_Total_Points`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Meet`.`EventExample`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Meet`.`EventExample` (
  `idEvents` INT NOT NULL AUTO_INCREMENT,
  `event_name` VARCHAR(45) NULL,
  `heat_flight` INT NULL,
  `athlete` INT NULL,
  `athlete_team` INT NULL,
  `performance` FLOAT NULL,
  `wind` FLOAT NULL,
  `points_won` FLOAT NULL,
  `place` FLOAT NULL,
  PRIMARY KEY (`idEvents`),
  INDEX `athlete_idx` (`athlete` ASC),
  INDEX `team_idx` (`athlete_team` ASC),
  CONSTRAINT `fk_Athlete_Team`
    FOREIGN KEY (`athlete`)
    REFERENCES `Meet`.`Athletes` (`idAthletes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Event_Team`
    FOREIGN KEY (`athlete_team`)
    REFERENCES `Meet`.`Teams` (`idTeams`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
